'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Building2, CheckCircle2, Clock3, Factory, RefreshCw, Truck, Users } from 'lucide-react';
import { api } from '../../lib/api';

type Tab = 'warehouses' | 'suppliers' | 'purchases' | 'shipments';
interface OperationsPageProps { cardClass: string; darkMode?: boolean; }

export default function OperationsPage({ cardClass, darkMode = false }: OperationsPageProps) {
  const [tab, setTab] = useState<Tab>('warehouses'); const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { const data = tab === 'warehouses' ? await api.warehouses() : tab === 'suppliers' ? await api.suppliers() : tab === 'purchases' ? await api.purchases() : await api.shipments(); setRows(data as any[]); setMessage(null); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load operations data'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [tab]);
  const recalculateSupplier = async (id: string) => { try { await api.recalculateSupplierReliability(id); setMessage('Supplier reliability recalculated.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to recalculate supplier'); } };
  const updatePurchase = async (id: string, status: string) => { try { if (status === 'completed') await api.receivePurchase(id); else await api.updatePurchaseStatus(id, status); setMessage('Purchase order updated.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update purchase order'); } };
  const updateShipment = async (id: string, status: string) => { try { await api.updateShipmentStatus(id, status, 'Operations desk'); setMessage('Shipment status updated.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update shipment'); } };
  const summary = useMemo(() => ({ total: rows.length, active: rows.filter((row) => !['completed', 'delivered', 'inactive'].includes(row.status)).length, healthy: rows.filter((row) => (row.reliabilityMetrics?.overallScore || row.currentUtilization || 0) >= 80).length }), [rows]);
  const tabs: Array<[Tab, string, React.ComponentType<{ className?: string }>]> = [['warehouses', 'Facilities', Building2], ['suppliers', 'Suppliers', Users], ['purchases', 'Purchases', Factory], ['shipments', 'Shipments', Truck]];

  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Network control tower</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Operations center</h1><p className="mt-2 text-sm text-slate-500">A live view of facilities, inbound supply, partners, and outbound movement.</p></div><button onClick={() => void load()} className="flex items-center justify-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-medium transition hover:bg-slate-500/10"><RefreshCw className="h-4 w-4" />Refresh live data</button></div>
    {message && <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}
    <div className="grid grid-cols-2 gap-4 xl:grid-cols-4"><SummaryCard cardClass={cardClass} label="Records in view" value={summary.total} icon={<Factory className="h-5 w-5" />} tone="blue" /><SummaryCard cardClass={cardClass} label="Active workflows" value={summary.active} icon={<Clock3 className="h-5 w-5" />} tone="amber" /><SummaryCard cardClass={cardClass} label="Healthy signals" value={summary.healthy} icon={<CheckCircle2 className="h-5 w-5" />} tone="green" /><SummaryCard cardClass={cardClass} label="Live connection" value="ON" icon={<ArrowUpRight className="h-5 w-5" />} tone="cyan" /></div>
    <div className="grid grid-cols-2 gap-2 md:grid-cols-4">{tabs.map(([value, label, Icon]) => <button key={value} onClick={() => setTab(value)} className={`flex items-center justify-center gap-2 rounded-xl border p-3 text-sm font-medium transition ${tab === value ? 'border-blue-500 bg-blue-500/10 text-blue-600 shadow-sm' : 'hover:bg-slate-500/10'}`}><Icon className="h-4 w-4" />{label}</button>)}</div>
    <section className={`rounded-2xl border p-5 shadow-sm sm:p-6 ${cardClass}`}>{loading ? <div className="py-16 text-center text-sm text-slate-500">Loading live operations data…</div> : <>{tab === 'warehouses' && <WarehouseList rows={rows} darkMode={darkMode} />}{tab === 'suppliers' && <SupplierList rows={rows} onRecalculate={recalculateSupplier} />}{tab === 'purchases' && <PurchaseList rows={rows} onUpdate={updatePurchase} />}{tab === 'shipments' && <ShipmentList rows={rows} onUpdate={updateShipment} />}</>}</section>
  </div>;
}

function SummaryCard({ cardClass, label, value, icon, tone }: { cardClass: string; label: string; value: string | number; icon: React.ReactNode; tone: string }) { return <div className={`rounded-2xl border p-5 shadow-sm ${cardClass}`}><div className="flex items-start justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.11em] text-slate-500">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div><div className={`rounded-xl p-2.5 ${tone === 'green' ? 'bg-emerald-500/10 text-emerald-500' : tone === 'amber' ? 'bg-amber-500/10 text-amber-500' : tone === 'cyan' ? 'bg-cyan-500/10 text-cyan-500' : 'bg-blue-500/10 text-blue-500'}`}>{icon}</div></div></div>; }
function WarehouseList({ rows, darkMode }: { rows: any[]; darkMode: boolean }) { return <div className="grid gap-4 md:grid-cols-2">{rows.map((warehouse) => { const utilization = Number(warehouse.currentUtilization || 0); return <div key={warehouse._id} className="rounded-xl border p-5 transition hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{warehouse.name}</h2><p className="mt-1 text-sm text-slate-500">{warehouse.location?.city || 'Location pending'}, {warehouse.location?.state || ''}</p></div><span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-medium text-emerald-600">{warehouse.status || 'active'}</span></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Capacity utilization</span><span className="font-semibold">{utilization}%</span></div><div className="h-2 rounded-full bg-slate-200/70"><div className={`h-2 rounded-full ${utilization > 85 ? 'bg-amber-500' : 'bg-cyan-500'}`} style={{ width: `${Math.min(100, utilization)}%` }} /></div></div><div className="mt-5 grid grid-cols-3 gap-3 border-t pt-4"><Metric label="Capacity" value={warehouse.capacity || '—'} /><Metric label="Utilization" value={`${utilization}%`} /><Metric label="Manager" value={warehouse.manager?.name || '—'} /></div>{darkMode && <span className="sr-only">Dark mode active</span>}</div>; })}{!rows.length && <EmptyState label="No warehouse records found." />}</div>; }
function SupplierList({ rows, onRecalculate }: { rows: any[]; onRecalculate: (id: string) => void }) { return <div className="grid gap-3">{rows.map((supplier) => { const score = supplier.reliabilityMetrics?.overallScore || 0; return <div key={supplier._id} className="flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-violet-500/10 p-2.5 text-violet-500"><Users className="h-5 w-5" /></div><div><p className="font-semibold">{supplier.name}</p><p className="mt-1 text-sm text-slate-500">{supplier.categories?.join(', ') || 'General supply'} · {supplier.deliveryInfo?.leadTime || '—'} day lead time</p></div></div><div className="flex items-center gap-3"><div className="text-right"><p className="text-xs text-slate-500">Reliability</p><p className={`text-lg font-semibold ${score >= 80 ? 'text-emerald-600' : 'text-amber-600'}`}>{score}/100</p></div><button onClick={() => onRecalculate(String(supplier._id))} className="rounded-lg border px-3 py-2 text-xs font-medium transition hover:bg-slate-500/10">Recalculate</button></div></div>; })}{!rows.length && <EmptyState label="No supplier records found." />}</div>; }
function PurchaseList({ rows, onUpdate }: { rows: any[]; onUpdate: (id: string, status: string) => void }) { return <div className="grid gap-3">{rows.map((purchase) => <div key={purchase._id} className="flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{purchase.purchaseOrderNumber}</p><p className="mt-1 text-sm text-slate-500">{purchase.product?.name || 'Product'} · {purchase.quantity} units</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-blue-500/10 px-2.5 py-1 text-xs font-medium text-blue-600">{purchase.status}</span>{purchase.status === 'approved' && <Action onClick={() => onUpdate(String(purchase._id), 'ordered')} label="Mark ordered" />}{purchase.status === 'delivered' && <Action onClick={() => onUpdate(String(purchase._id), 'completed')} label="Complete receipt" />}</div></div>)}{!rows.length && <EmptyState label="No purchase orders found." />}</div>; }
function ShipmentList({ rows, onUpdate }: { rows: any[]; onUpdate: (id: string, status: string) => void }) { return <div className="grid gap-3">{rows.map((shipment) => <div key={shipment._id} className="flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-cyan-500/10 p-2.5 text-cyan-500"><Truck className="h-5 w-5" /></div><div><p className="font-semibold">{shipment.trackingNumber || 'Tracking pending'}</p><p className="mt-1 text-sm text-slate-500">{shipment.destination?.name || 'Destination pending'} · {shipment.carrier?.name || 'Carrier pending'}</p></div></div><div className="flex items-center gap-3"><span className="rounded-full bg-indigo-500/10 px-2.5 py-1 text-xs font-medium text-indigo-600">{shipment.status}</span>{shipment.status === 'processing' && <Action onClick={() => onUpdate(String(shipment._id), 'in-transit')} label="Mark in transit" />}{shipment.status === 'in-transit' && <Action onClick={() => onUpdate(String(shipment._id), 'delivered')} label="Mark delivered" />}</div></div>)}{!rows.length && <EmptyState label="No shipment records found." />}</div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><div className="text-xs text-slate-500">{label}</div><div className="mt-1 truncate text-sm font-semibold">{value}</div></div>; }
function Action({ onClick, label }: { onClick: () => void; label: string }) { return <button onClick={onClick} className="rounded-lg border px-3 py-2 text-xs font-medium transition hover:bg-slate-500/10">{label}</button>; }
function EmptyState({ label }: { label: string }) { return <div className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-500">{label}</div>; }
