'use client';

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { CheckCircle2, ChevronDown, CircleDot, MapPin, PackageCheck, PackagePlus, RotateCcw, Search, Truck, XCircle } from 'lucide-react';
import { api } from '../../lib/api';
import { CustomerOrder, InventoryItem, OrderStatus } from '../../types';

interface OrdersPageProps { cardClass: string; inventory?: InventoryItem[]; darkMode?: boolean; }
const statuses: OrderStatus[] = ['pending', 'confirmed', 'processing', 'packed', 'shipped', 'delivered', 'cancelled', 'returned'];
const statusStyles: Record<string, string> = { pending: 'bg-amber-500/10 text-amber-600', confirmed: 'bg-blue-500/10 text-blue-600', processing: 'bg-violet-500/10 text-violet-600', packed: 'bg-cyan-500/10 text-cyan-600', shipped: 'bg-indigo-500/10 text-indigo-600', delivered: 'bg-emerald-500/10 text-emerald-600', cancelled: 'bg-rose-500/10 text-rose-600', returned: 'bg-slate-500/10 text-slate-500' };

export default function OrdersPage({ cardClass, inventory = [], darkMode = false }: OrdersPageProps) {
  const [orders, setOrders] = useState<CustomerOrder[]>([]); const [liveInventory, setLiveInventory] = useState<InventoryItem[]>(inventory); const [selectedStatus, setSelectedStatus] = useState(''); const [search, setSearch] = useState(''); const [isCreating, setIsCreating] = useState(false); const [message, setMessage] = useState<string | null>(null); const [isGeocoding, setIsGeocoding] = useState(false); const [showForm, setShowForm] = useState(false); const geocodeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [form, setForm] = useState({ name: '', email: '', phone: '', street: '', city: '', state: '', zipCode: '', lat: '', lng: '', productId: '', quantity: '1' });
  const loadOrders = async () => { const rows = await api.orders(`limit=100${selectedStatus ? `&status=${selectedStatus}` : ''}`); setOrders(rows as CustomerOrder[]); };
  useEffect(() => { loadOrders().catch((error) => setMessage(error instanceof Error ? error.message : 'Unable to load orders')); }, [selectedStatus]);
  useEffect(() => { let cancelled = false; const refresh = async () => { try { const rows = await api.inventory('limit=100'); if (!cancelled) setLiveInventory(rows.map((row: any) => ({ id: String(row._id || row.id), warehouseId: String(row.warehouse?.id || ''), productId: String(row.product?.id || ''), sku: row.product?.sku || '', category: row.product?.category, unitPrice: row.product?.price || 0, product: row.product?.name || row.product?.sku || 'Unknown product', current: row.availableQuantity ?? row.quantity ?? 0, forecasted: row.availableQuantity ?? row.quantity ?? 0, reorderLevel: row.reorderPoint || 0, trend: 'down' }))); } catch { /* keep parent snapshot */ } }; void refresh(); const interval = window.setInterval(refresh, 15000); return () => { cancelled = true; window.clearInterval(interval); }; }, []);
  const addressQuery = [form.street, form.city, form.state, form.zipCode].filter(Boolean).join(', ');
  useEffect(() => { if (addressQuery.length < 6) return; if (geocodeTimer.current) clearTimeout(geocodeTimer.current); geocodeTimer.current = setTimeout(async () => { try { setIsGeocoding(true); const location = await api.geocode(addressQuery); setForm((current) => ({ ...current, lat: location.latitude.toFixed(6), lng: location.longitude.toFixed(6) })); } catch { setMessage('Location could not be found automatically. Enter coordinates manually.'); } finally { setIsGeocoding(false); } }, 700); return () => { if (geocodeTimer.current) clearTimeout(geocodeTimer.current); }; }, [addressQuery]);
  const inventoryData = liveInventory.length ? liveInventory : inventory; const selectedProduct = inventoryData.find((item) => item.productId === form.productId); const updateForm = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const filteredOrders = useMemo(() => orders.filter((order) => `${order.orderNumber} ${order.customer?.name} ${order.customer?.email}`.toLowerCase().includes(search.toLowerCase())), [orders, search]);
  const metrics = { open: orders.filter((order) => !['delivered', 'cancelled', 'returned'].includes(order.status)).length, processing: orders.filter((order) => ['processing', 'packed'].includes(order.status)).length, shipped: orders.filter((order) => ['shipped', 'delivered'].includes(order.status)).length, value: orders.reduce((sum, order) => sum + (order.orderTotal?.totalAmount || 0), 0) };

  const createOrder = async (event: React.FormEvent) => { event.preventDefault(); if (!selectedProduct?.productId || !selectedProduct.category) return setMessage('Choose a product from live inventory.'); const quantity = Number(form.quantity); if (!Number.isInteger(quantity) || quantity < 1) return setMessage('Quantity must be a positive whole number.'); try { setIsCreating(true); await api.createOrder({ customer: { name: form.name, email: form.email, phone: form.phone, address: { street: form.street, city: form.city, state: form.state, country: 'India', zipCode: form.zipCode, coordinates: { lat: Number(form.lat), lng: Number(form.lng) } } }, items: [{ product: { id: selectedProduct.productId, name: selectedProduct.product, sku: selectedProduct.sku || selectedProduct.product, category: selectedProduct.category }, quantity, unitPrice: selectedProduct.unitPrice || 0, totalPrice: (selectedProduct.unitPrice || 0) * quantity }], orderTotal: { subtotal: (selectedProduct.unitPrice || 0) * quantity, tax: 0, shippingCost: 0, totalAmount: (selectedProduct.unitPrice || 0) * quantity }, priority: 'medium', paymentStatus: 'pending', paymentMethod: 'cash_on_delivery' }); setMessage('Order created and stock reserved.'); setShowForm(false); await loadOrders(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create order'); } finally { setIsCreating(false); } };
  const execute = async (action: string, order: CustomerOrder) => { try { if (action === 'confirm') await api.updateOrderStatus(order._id, 'confirmed'); if (action === 'fulfill') await api.fulfillOrder(order._id); if (action === 'pack') await api.updateOrderStatus(order._id, 'packed'); if (action === 'ship') await api.createOrderShipment(order._id); if (action === 'cancel') await api.cancelOrder(order._id); if (action === 'return') await api.returnOrder(order._id); setMessage(`Order ${order.orderNumber} updated.`); await loadOrders(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Order action failed'); } };

  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Fulfillment control</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Order management</h1><p className="mt-2 text-sm text-slate-500">Move orders from reservation to delivery with complete stock visibility.</p></div><button onClick={() => setShowForm((value) => !value)} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700"><PackagePlus className="h-4 w-4" />New order</button></div>
    {message && <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}
    <div className="grid grid-cols-2 gap-4 xl:grid-cols-4"><Metric cardClass={cardClass} label="Open orders" value={String(metrics.open)} detail="Awaiting completion" tone="blue" /><Metric cardClass={cardClass} label="In fulfillment" value={String(metrics.processing)} detail="Processing or packed" tone="violet" /><Metric cardClass={cardClass} label="Shipped / delivered" value={String(metrics.shipped)} detail="Outbound movement" tone="green" /><Metric cardClass={cardClass} label="Order value" value={`₹${metrics.value.toLocaleString()}`} detail="Current result set" tone="amber" /></div>
    {showForm && <form onSubmit={createOrder} className={`grid grid-cols-1 gap-3 rounded-2xl border p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-4 ${cardClass}`}><div className="sm:col-span-2 lg:col-span-4"><h2 className="text-lg font-semibold">Create and reserve order</h2><p className="mt-1 text-sm text-slate-500">Live inventory is required. Stock is reserved when the order is created.</p></div>{(['name', 'email', 'phone', 'street', 'city', 'state', 'zipCode', 'lat', 'lng'] as const).map((key) => <input key={key} required value={form[key]} onChange={(event) => updateForm(key, event.target.value)} type={key === 'email' ? 'email' : 'text'} placeholder={key === 'lat' ? 'Latitude' : key === 'lng' ? 'Longitude' : key.replace(/([A-Z])/g, ' $1')} className="rounded-lg border bg-transparent p-2.5 text-sm outline-none focus:border-blue-500" />)}<select required value={form.productId} onChange={(event) => updateForm('productId', event.target.value)} className="rounded-lg border bg-transparent p-2.5 text-sm"><option value="">{inventoryData.length ? 'Select live inventory' : 'No inventory available'}</option>{inventoryData.filter((item) => item.productId && item.current > 0).map((item) => <option key={item.id} value={item.productId}>{item.product} ({item.current} available)</option>)}</select><input required min="1" type="number" value={form.quantity} onChange={(event) => updateForm('quantity', event.target.value)} placeholder="Quantity" className="rounded-lg border bg-transparent p-2.5 text-sm" /><div className="flex items-center gap-3 lg:col-span-2"><button disabled={isCreating} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><PackagePlus className="h-4 w-4" />{isCreating ? 'Creating…' : 'Create and reserve'}</button>{isGeocoding && <span className="text-xs text-slate-500">Finding location…</span>}</div></form>}
    <section className={`rounded-2xl border p-5 shadow-sm sm:p-6 ${cardClass}`}><div className="mb-5 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-semibold">Order queue</h2><p className="mt-1 text-sm text-slate-500">Search and progress live customer orders.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Search className="h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order or customer" className="w-full bg-transparent outline-none sm:w-52" /></label><label className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><ChevronDown className="h-4 w-4 text-slate-400" /><select value={selectedStatus} onChange={(event) => setSelectedStatus(event.target.value)} className="bg-transparent outline-none"><option value="">All statuses</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label></div></div><div className="grid gap-4">{filteredOrders.map((order) => <OrderCard key={order._id} order={order} execute={execute} darkMode={darkMode} />)}{!filteredOrders.length && <div className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-500">No orders match the current filters.</div>}</div></section>
  </div>;
}

function Metric({ cardClass, label, value, detail, tone }: { cardClass: string; label: string; value: string; detail: string; tone: string }) { return <div className={`rounded-2xl border p-5 shadow-sm ${cardClass}`}><div className="flex items-start justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight">{value}</p></div><div className={`rounded-xl p-2 ${tone === 'green' ? 'bg-emerald-500/10 text-emerald-500' : tone === 'amber' ? 'bg-amber-500/10 text-amber-500' : tone === 'violet' ? 'bg-violet-500/10 text-violet-500' : 'bg-blue-500/10 text-blue-500'}`}><CircleDot className="h-4 w-4" /></div></div><p className="mt-3 text-xs text-slate-500">{detail}</p></div>; }

function OrderCard({ order, execute, darkMode }: { order: CustomerOrder; execute: (action: string, order: CustomerOrder) => void; darkMode: boolean }) { const status = order.status; return <article className="rounded-xl border p-4 transition hover:shadow-md sm:p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div className="flex gap-3"><div className="rounded-xl bg-blue-500/10 p-2.5 text-blue-500"><PackageCheck className="h-5 w-5" /></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{order.orderNumber}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusStyles[status] || 'bg-slate-500/10 text-slate-500'}`}>{status}</span></div><p className="mt-1 text-sm text-slate-500">{order.customer?.name} · {order.customer?.email}</p></div></div><div className="flex flex-wrap gap-2">{status === 'pending' && <Action onClick={() => execute('confirm', order)} icon={<CheckCircle2 className="h-3.5 w-3.5" />} label="Confirm" />}{status === 'confirmed' && <Action onClick={() => execute('fulfill', order)} icon={<PackagePlus className="h-3.5 w-3.5" />} label="Fulfill" />}{status === 'processing' && <><Action onClick={() => execute('pack', order)} icon={<PackageCheck className="h-3.5 w-3.5" />} label="Pack" /><Action onClick={() => execute('ship', order)} icon={<Truck className="h-3.5 w-3.5" />} label="Ship" /></>}{['pending', 'confirmed'].includes(status) && <Action onClick={() => execute('cancel', order)} icon={<XCircle className="h-3.5 w-3.5" />} label="Cancel" />}{['processing', 'packed', 'shipped', 'delivered'].includes(status) && <Action onClick={() => execute('return', order)} icon={<RotateCcw className="h-3.5 w-3.5" />} label="Return" />}</div></div><div className="mt-5 grid gap-4 border-t pt-4 text-sm sm:grid-cols-4"><div><p className="text-xs text-slate-500">Items</p><p className="mt-1 font-medium">{order.items?.map((item) => `${item.product.name} × ${item.quantity}`).join(', ')}</p></div><div><p className="text-xs text-slate-500">Order value</p><p className="mt-1 font-semibold">₹{(order.orderTotal?.totalAmount || 0).toLocaleString()}</p></div><div><p className="text-xs text-slate-500">Warehouse</p><p className="mt-1 flex items-center gap-1 font-medium"><MapPin className="h-3.5 w-3.5 text-slate-400" />{order.assignedWarehouse?.name || 'Unassigned'}</p></div><div><p className="text-xs text-slate-500">Tracking</p><p className={`mt-1 font-medium ${darkMode ? 'text-slate-200' : 'text-slate-700'}`}>{order.tracking?.trackingNumber || 'Not generated'}</p></div></div></article>; }
function Action({ onClick, icon, label }: { onClick: () => void; icon: React.ReactNode; label: string }) { return <button onClick={onClick} className="flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium transition hover:bg-slate-500/10">{icon}{label}</button>; }
