'use client';

import React, { useEffect, useState } from 'react';
import { AlertTriangle, BarChart3, Download, FileDown, Package, Printer, RefreshCw, Truck } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../../lib/api';

interface ReportsPageProps { cardClass: string; darkMode?: boolean; }

export default function ReportsPage({ cardClass, darkMode = false }: ReportsPageProps) {
  const [warehouses, setWarehouses] = useState<any[]>([]); const [warehouse, setWarehouse] = useState(''); const [range, setRange] = useState('30'); const [data, setData] = useState<any>({ inventory: {}, purchases: {}, shipments: {}, alerts: {} }); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = async () => { setLoading(true); const end = new Date(); const start = new Date(end.getTime() - Number(range) * 24 * 60 * 60 * 1000); const query = new URLSearchParams({ startDate: start.toISOString(), endDate: end.toISOString() }); if (warehouse) { query.set('warehouse', warehouse); query.set('warehouseId', warehouse); } try { const [inventory, purchases, shipments, alerts] = await Promise.all([api.inventorySummary(warehouse), api.purchaseAnalytics(query.toString()), api.shipmentAnalytics(query.toString()), api.alertAnalytics(query.toString())]); setData({ inventory, purchases, shipments, alerts }); setMessage(null); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load analytics'); } finally { setLoading(false); } };
  useEffect(() => { api.warehouses().then((items) => setWarehouses(items as any[])).catch(() => undefined); }, []); useEffect(() => { void load(); }, [warehouse, range]);
  const exportCsv = () => { const rows = [['Metric', 'Value'], ['Total inventory', String(data.inventory?.totalItems || 0)], ['Purchase spend', String(data.purchases?.totalAmount || 0)], ['Shipments', String(data.shipments?.totalShipments || 0)], ['On-time delivery rate', `${data.shipments?.onTimeDeliveryRate || 0}%`], ['Unresolved alerts', String(data.alerts?.unresolvedAlerts || 0)]]; const blob = new Blob([rows.map((row) => row.join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'spark-operations-report.csv'; anchor.click(); URL.revokeObjectURL(url); };
  const trends = (data.shipments?.monthlyTrends || []).map((item: any) => ({ month: `${item._id.month}/${item._id.year}`, delivered: item.delivered, delayed: item.delayed })); const purchaseCategories = (data.purchases?.categoryBreakdown || []).map((item: any) => ({ category: item._id, amount: item.totalAmount })); const chartStyle = { fill: darkMode ? '#94a3b8' : '#64748b', fontSize: 11 }; const tooltipStyle = { borderRadius: 12, border: 0, background: darkMode ? '#172033' : '#0f172a', color: '#fff' };
  const kpis = [{ label: 'Inventory units', value: Number(data.inventory?.totalItems || 0).toLocaleString(), icon: <Package className="h-5 w-5" />, tone: 'blue' }, { label: 'Purchase spend', value: `₹${Number(data.purchases?.totalAmount || 0).toLocaleString()}`, icon: <BarChart3 className="h-5 w-5" />, tone: 'violet' }, { label: 'Shipments', value: data.shipments?.totalShipments || 0, icon: <Truck className="h-5 w-5" />, tone: 'cyan' }, { label: 'On-time delivery', value: `${data.shipments?.onTimeDeliveryRate || 0}%`, icon: <FileDown className="h-5 w-5" />, tone: 'green' }, { label: 'Open alerts', value: data.alerts?.unresolvedAlerts || 0, icon: <AlertTriangle className="h-5 w-5" />, tone: 'amber' }];
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Decision intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Reports & insights</h1><p className="mt-2 text-sm text-slate-500">Live operational performance across inventory, purchasing, delivery, and exceptions.</p></div><div className="flex gap-2"><button onClick={exportCsv} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2.5 text-sm font-semibold text-white hover:bg-emerald-700"><Download className="h-4 w-4" />CSV</button><button onClick={() => window.print()} className="flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm font-medium hover:bg-slate-500/10"><Printer className="h-4 w-4" />Print</button></div></div>
    <div className={`flex flex-col gap-4 rounded-2xl border p-4 shadow-sm sm:flex-row sm:items-end ${cardClass}`}><label className="text-xs font-medium uppercase tracking-wide text-slate-500">Date range<select value={range} onChange={(event) => setRange(event.target.value)} className="mt-1 block rounded-lg border bg-transparent p-2.5 text-sm normal-case tracking-normal"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 3 months</option><option value="365">Last year</option></select></label><label className="text-xs font-medium uppercase tracking-wide text-slate-500">Warehouse<select value={warehouse} onChange={(event) => setWarehouse(event.target.value)} className="mt-1 block min-w-52 rounded-lg border bg-transparent p-2.5 text-sm normal-case tracking-normal"><option value="">All warehouses</option>{warehouses.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><button onClick={() => void load()} className="flex items-center justify-center gap-2 rounded-lg border px-3 py-2.5 text-sm font-medium hover:bg-slate-500/10"><RefreshCw className="h-4 w-4" />{loading ? 'Loading…' : 'Refresh'}</button></div>
    {message && <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">{message}</div>}
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-5">{kpis.map((item) => <Kpi key={item.label} cardClass={cardClass} {...item} />)}</div>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-[1.35fr_1fr]"><Panel cardClass={cardClass} title="Delivery performance" subtitle={`Shipment movement over the last ${range} days`}><ChartEmpty visible={!trends.length} label="Shipment trend data will appear as deliveries are recorded."><ResponsiveContainer width="100%" height="100%"><LineChart data={trends} margin={{ top: 10, right: 8, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke={darkMode ? '#334155' : '#e2e8f0'} /><XAxis dataKey="month" tick={chartStyle} axisLine={false} tickLine={false} /><YAxis tick={chartStyle} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} /><Line type="monotone" dataKey="delivered" stroke="#10b981" strokeWidth={3} name="Delivered" dot={{ r: 3 }} /><Line type="monotone" dataKey="delayed" stroke="#f43f5e" strokeWidth={2} name="Delayed" /></LineChart></ResponsiveContainer></ChartEmpty></Panel><Panel cardClass={cardClass} title="Purchase allocation" subtitle="Spend by product category"><ChartEmpty visible={!purchaseCategories.length} label="Purchase category data will appear after purchase orders are recorded."><ResponsiveContainer width="100%" height="100%"><BarChart data={purchaseCategories} margin={{ top: 10, right: 8, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke={darkMode ? '#334155' : '#e2e8f0'} /><XAxis dataKey="category" tick={chartStyle} axisLine={false} tickLine={false} /><YAxis tick={chartStyle} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="amount" name="Spend" fill="#8b5cf6" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></ChartEmpty></Panel></div>
    <section className={`rounded-2xl border p-5 shadow-sm sm:p-6 ${cardClass}`}><div className="mb-5"><h2 className="text-lg font-semibold">Inventory status distribution</h2><p className="mt-1 text-sm text-slate-500">Current stock state across the selected scope.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{(data.inventory?.statusBreakdown || []).map((item: any) => <div key={item._id} className="rounded-xl border p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{item._id.replace('_', ' ')}</p><p className="mt-2 text-2xl font-semibold">{Number(item.totalQuantity || 0).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">{item.count} records</p></div>)}{!(data.inventory?.statusBreakdown || []).length && <div className="col-span-full rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Inventory status data will appear after live stock is recorded.</div>}</div></section>
  </div>;
}

function Kpi({ cardClass, label, value, icon, tone }: { cardClass: string; label: string; value: string | number; icon: React.ReactNode; tone: string }) { const color = tone === 'green' ? 'bg-emerald-500/10 text-emerald-500' : tone === 'amber' ? 'bg-amber-500/10 text-amber-500' : tone === 'violet' ? 'bg-violet-500/10 text-violet-500' : tone === 'cyan' ? 'bg-cyan-500/10 text-cyan-500' : 'bg-blue-500/10 text-blue-500'; return <div className={`rounded-2xl border p-4 shadow-sm ${cardClass}`}><div className="flex items-start justify-between"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><div className={`rounded-lg p-2 ${color}`}>{icon}</div></div><p className="mt-4 truncate text-2xl font-semibold">{value}</p></div>; }
function Panel({ cardClass, title, subtitle, children }: { cardClass: string; title: string; subtitle: string; children: React.ReactNode }) { return <div className={`rounded-2xl border p-5 shadow-sm sm:p-6 ${cardClass}`}><div className="mb-4"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><div className="h-[300px]">{children}</div></div>; }
function ChartEmpty({ visible, label, children }: { visible: boolean; label: string; children: React.ReactNode }) { return visible ? <div className="flex h-full items-center justify-center rounded-xl border border-dashed text-center text-sm text-slate-500">{label}</div> : <>{children}</>; }
